repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.2
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--init
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--compact
          - --args=--download-external-modules DOWNLOAD_EXTERNAL_MODULES
#          - --args=--hard-fail-on MEDIUM
