repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.2
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
        args:
          - --tf-init-args=-backend=false
      - id: terraform_trivy
        args:
          - --args=--severity=MEDIUM,HIGH,CRITICAL
          - --args=--skip-dirs=.external_modules
      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--compact
          - --args=--download-external-modules DOWNLOAD_EXTERNAL_MODULES
          - --args=--hard-fail-on MEDIUM
