apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rollouts-demo
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - rollouts-demo
              topologyKey: topology.kubernetes.io/zone
      securityContext:
        sysctls:
          - name: net.ipv4.tcp_congestion_control
            value: bbr

# https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/
