apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: rollouts-demo
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: rollouts-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-demo
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: rollouts-demo
spec:
  defaultBackend:
    service:
      name: rollouts-demo
      port:
        number: 80
