# Source: https://docs.cloudposse.com/layers/spacelift/#feature-branch
name: Plan Affected Spacelift Stacks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Atmos Affected Stacks Trigger Spacelift
        uses: cloudposse/github-action-atmos-affected-trigger-spacelift@v2
        with:
          atmos-config-path: ./rootfs/usr/local/etc/atmos
          github-token: ${{ secrets.PUSH_TOKEN }}
