name: Checkov

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: .

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.working-directory }}
          output_format: cli
          output_file_path: console
