name: Golden image CI

on:
  workflow_run:
    workflows:
      - Golden image IDs comparison
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

jobs:
  golden-image-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      working_dir: nodes/images
    outputs:
      flag: ${{ steps.set-flag.outputs.flag }}
    if: |
      (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.flag == 'true') ||
      github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: Initialize machine image builder
        run: packer init ${{ env.working_dir }}
      - name: Build machine image
        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          echo -n "${OCI_PRIVATE_KEY}" > certificates/mtweeman@gmail.com_2024-03-02T19_23_13.049Z.pem
          packer build ${{ env.working_dir }}
      - name: Set flag
        id: set-flag
        run: |
          echo "flag=true" >> $GITHUB_OUTPUT
