name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  static-analyzers-aggregator:
    name: Static analysis
    uses: ./.github/workflows/static-analyzers-aggregator.yaml
