name: Static analyzers aggregator pre-commit

on:
  workflow_call:

permissions:
  contents: read

jobs:
  static-analysis-pre-commit:
    name: Static analysis pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Restore cached static analyzers
        uses: actions/cache/restore@v4
        with:
          path: .
          key: static-analyzers-pre-commit
      - name: Static analysis
        run: |
          pre-commit run --all-files
