name: Static analyzers aggregator

on:
  workflow_call:

permissions:
  contents: read

jobs:
  static-analyzers-aggregator:
    name: Static analyzers aggregator
    runs-on: ubuntu-latest
    container:
      image: hajlesilesia/toolbox:1.3.3

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit-zipapp
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run static analysis
        run: |
          pre-commit run --all-files --hook-stage manual
