name: Terraform fmt

on:
  workflow_call:
    inputs:
      terraform-version:
        type: string
        required: false
        default: latest
      working-directory:
        type: string
        required: false
        default: .

jobs:
  terraform-fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up provisioning tool
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Terraform fmt
        working-directory: ${{ inputs.working-directory }}
        run: |
          terraform fmt \
          -check \
          -diff \
          -recursive
