name: Terraform validate

on:
  workflow_call:
    inputs:
      terraform-version:
        type: string
        required: false
        default: latest
      working-directory:
        type: string
        required: false
        default: .

jobs:
  terraform-validate:
    name: Terraform validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up provisioning tool
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}
      - name: Terraform validate
        working-directory: ${{ inputs.working-directory }}
        run: |
          validation_failed=false
          
          while IFS= read -r directory; do
            echo "Validating ${directory}"
            terraform -chdir="${directory}" init -backend=false
            terraform -chdir="${directory}" validate
          
            if (( $? != 0 )); then
              echo "Validation failed in ${directory}"
              validation_failed=true
            fi
          done < <(find "$(pwd)" -type f -name ".terraform.lock.hcl" -exec dirname {} \; | sort | uniq)
          
          if [ "${validation_failed}" = true ]; then
            exit 1
          fi
