name: TFLint

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: false
        default: .

permissions:
  contents: read

jobs:
  tflint:
    name: TFLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Cache
        uses: actions/cache/restore@v4
        with:
          path: /usr/local/bin/tflint
          key: tflint
      - name: TFLint
        working-directory: ${{ inputs.working-directory }}
        run: |
          tflint --init
          tflint --recursive --config "$(pwd)/.tflint.hcl"
