name: Toolbox CI

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
    paths:
      - "toolbox/**"
  workflow_dispatch:

jobs:
  image-build:
    name: Build image
    uses: hajle-silesia/.github/.github/workflows/shared-image-build.yaml@v2.4.0
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
      dir: toolbox
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}
